trigger:
- main  # Adjust this to match your desired trigger pattern

pool:
  name: Self-Hosted-Agent

steps:
- task: S3Upload@1
  inputs:
    awsCredentials: 'logixos-task1-connection'
    regionName: 'us-west-1'
    bucketName: 'logixos-task'
    globExpressions: '**'
    filesAcl: 'public-read'
    keyManagement: 'awsManaged'
    encryptionAlgorithm: 'AES256'
    logRequest: true
    logResponse: true